### ISSUE TITLE
MIP 页面

### ISSUE THREAD

**Issue by coo11** [yulanggong/celery#2]
## 破解“禁用复制”失败的网址
https://m.leha.com/mip/1356594

## 操作系统以及版本号，浏览器以及版本号
Windows、iOS，Chrome、Safari

## 我猜测复制失败的原因
有些对象方法被覆盖

**Comment by yulanggong** [comment]
这个是因为 custom element 的初始化机制导致的失败，还需要再研究下方案

**Comment by yulanggong** [comment]
这个页面的问题修复了，custom element 可以导致的其他问题还需要再研究下
